### ISSUE TITLE
Conch vss device ${id} is wrong

### ISSUE THREAD

**Issue by jemershaw** [joyent/conch-shell#184]
The shell is reporting incorrect information when running `conch vss device ${id}`.

The output shows the device is in a fail status, but the reports shows everything as pass. When I navigate the UI it shows disk_smart_status is failed.

|    DEVICE ID    | STATUS |              COMPLETED              |       VALIDATION PLAN        |         RESULTS         |
|-----------------|--------|-------------------------------------|------------------------------|-------------------------|
| S329229X8822018 | fail   | 2018-10-11 21:50:05.75677 +0000 UTC | Conch v1 Legacy Plan: Server | nics_num: pass          |
|                 |        |                                     |                              | product_name: pass      |
|                 |        |                                     |                              | cpu_temperature: pass   |
|                 |        |                                     |                              | cpu_count: pass         |
|                 |        |                                     |                              | sas_hdd_num: pass       |
|                 |        |                                     |                              | firmware_current: pass  |
|                 |        |                                     |                              | disk_temperature: pass  |
|                 |        |                                     |                              | switch_peers: pass      |
|                 |        |                                     |                              | dimm_count: pass        |
|                 |        |                                     |                              | usb_hdd_num: pass       |
|                 |        |                                     |                              | links_up: pass          |
|                 |        |                                     |                              | disk_smart_status: pass |
|                 |        |                                     |                              | slog_slot: pass         |
|                 |        |                                     |                              | ram_total: pass         |
|                 |        |                                     |                              | sas_ssd_num: pass       |

**Comment by sungo** [comment]
Looking at the raw json from the API, there's a failing validation that's not showing in the results column.

```
      {
        "category": "DISK",
        "component_id": null,
        "device_id": "S329229X8822018",
        "hardware_product_id": "8fcf6520-eac7-444d-bf67-7ba7ea0a0c73",
        "hint": null,
        "id": "fdee1c91-6908-4fb6-b694-4014497bdd08",
        "message": "No health reported for disk 8HGPR8XH",
        "order": 2,
        "status": "fail",
        "validation_id": "060f5993-252a-4e20-8fac-dba620e2a286"
      }
```

Will look to see why that's not being displayed.

**Comment by sungo** [comment]
#185 is the fix for this, as noted. In the display of results, if any result passed, all results were marked as 'pass'. The new output, rendered against the production database, follows:


|    DEVICE ID    | STATUS |              COMPLETED               |       VALIDATION PLAN        |                RESULTS                 |
|-----------------|--------|--------------------------------------|------------------------------|----------------------------------------|
| S329229X8822018 | fail   | 2018-10-12 19:42:24.461843 +0000 UTC | Conch v1 Legacy Plan: Server | disk_smart_status: fail                |
|                 |        |                                      |                              |   No health reported for disk 8HGPR8XH |
|                 |        |                                      |                              | usb_hdd_num: pass                      |
|                 |        |                                      |                              | cpu_temperature: pass                  |
|                 |        |                                      |                              | firmware_current: pass                 |
|                 |        |                                      |                              | switch_peers: pass                     |
|                 |        |                                      |                              | ram_total: pass                        |
|                 |        |                                      |                              | links_up: pass                         |
|                 |        |                                      |                              | sas_ssd_num: pass                      |
|                 |        |                                      |                              | nics_num: pass                         |
|                 |        |                                      |                              | sas_hdd_num: pass                      |
|                 |        |                                      |                              | slog_slot: pass                        |
|                 |        |                                      |                              | disk_temperature: pass                 |
|                 |        |                                      |                              | dimm_count: pass                       |
|                 |        |                                      |                              | cpu_count: pass                        |
|                 |        |                                      |                              | product_name: pass                     |

**Comment by sungo** [comment]
I'll backport this to the current production release and push out the fix in a few moments.
