### ISSUE TITLE
remind the user to relogin when the JWT is expired

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-shell#219]
On receiving a 403 response, it's not immediately obvious to the user that the (common) reason for this is that the JWT has expired. It would be helpful to check the profile file, and if it is expired, tell the user that they should run `conch profile relogin`.

probably overlaps with #120.

**Comment by sungo** [comment]
In theory, the shell auto-refreshes the token long before it expires. But, yeah, for infrequent users, this will be a problem.

A brief glance at the code flow leads me to think this is a bug, not a feature gap. In theory, things are calling `API.VerifyLogin` which will attempt to refresh the JWT if the token is out of bounds, time wise. If that refresh fails, the user should get a LoginFailed error. 

That said, there is a gap here where if the token hasn't expired yet, but the server has removed the token, the user will get a 403 value back on the shell. This happens because the VerifyLogin function bails out early if it thinks the token is still inside its freshness window.

Further, the code uses LoginFailed way too liberally in the Verify flow. That's going to lead to use confusion since there's no nuance in the messages.

So, congrats on uncovering a half-dozen issues in a single request :)

**Comment by karenetheridge** [comment]
🙇‍♀️
