### ISSUE TITLE
Conch-shell update

### ISSUE THREAD

**Issue by jemershaw** [joyent/conch-shell#71]
It would be nice if conch-shell would have it's own self update mechanism. Also having the ability to support different source locations but it should always default from pulling from github releases.

A few thoughts on how maybe this could function would be `conch self-update latest --source https://conch.joyent.us/release --version 10.0.0`

**Comment by sungo** [comment]
With the GH releases, I poll the API and grab file uRLs out of its payload. How do you see the "different source locations" working, since I figure it's kinda silly to ask those locations to support that same API?

**Comment by bdha** [comment]
Big +1 on self-updates, but:

I don't think we need to support anything other than GitHub Releases at this point. If someone wants to store our artifacts on some other backend, they can presumably sort that out themselves.

**Comment by sungo** [comment]
Makes sense. Internally, the code already knows how to talk to the GH releases API so it's just a matter of figuring out the safest way to update the binary.

**Comment by sungo** [comment]
Just as a reminder to myself: will need to take care that the smartos client knows to grab the 'solaris' build.

**Comment by jemershaw** [comment]
I didn't have anything in mind about the different sources just added it if there was a way we could do it similar to how imgadm pulls from different sources. As long as we are naming versions correctly then I think it should be easy to grab the correct os binary.

**Comment by sungo** [comment]
Just to get a thought of mine on the record, thinking about supporting non-github release endpoints, I think I feel pretty strongly about only ever supporting Github Releases. My thought is that the self-update command should only delivery officially supported binaries, particularly since a self-update command would necessarily overwrite the existing binary. Our officially supported binaries come out of Github Releases via CI. If self-update were to support unofficial sources, it could be difficult for us to debug because that 'conch' binary might have custom patches or be old or any number of situation that would nearly impossible for us to detect.

We could add support for pre-releases but thus far we've not had long-lived pre-releases. If life were to get super complicated, I'd suggest we add a notion of release "channels" like Chrome has, where you can opt into pre-releases. But for now, there's no need.
