### ISSUE TITLE
Address mow.cli breakages

### ISSUE THREAD

**Issue by lseppala** [joyent/conch-shell#90]
mow.cli introduces breaking changes that cause the build to fail

See: https://github.com/jawher/mow.cli/commit/3ff64ca21987cfa628bd8d1865162b7ccd6107d7

**Comment by sungo** [comment]
This affects mow.cli v1.0.4. We are currently pinned to 1.0.3

**Comment by jawher** [comment]
Hey !

I'm the maintainer of `mow.cli` and I just found it about this issue.

Just to clarify matters:

* in `v1.0.4` the codebase was refactored to move some of the code into internal packages
* however, I did take care not to break the public API, hence the minor version bump
* the problem is: conch-shell imports `mow.cli` using `gopkg.in/jawher/mow.cli.v1` instead of the canonical `github.com/jawher/mow.cli`
* and because of that, the top level package, can no longer import the internal packages.

One very easy fix is to simply use the canonical package name, as documented in the readme :)

**Comment by sungo** [comment]
Excellent. Thanks for the response, @jawher. Since we're using dep these days which can pin via tags, it shouldn't be an issue to move to the canonical repo name.
